### ISSUE TITLE
Build a basic front-end

### ISSUE THREAD

**Issue by Prajwalmithun** [Prajwalmithun/homomorphic_encryption#1]
# Todo 

## Framework to use: 
`flask`

## 1. Create a `home` page
`home` page contains: 
- [ ] `title` as `CAT Lovers 🐱 ❤️  VS Dog 🐕 ❤️  Lovers`
- [ ]  `introduction` in the middle of the page as `Welcome to the most awaited ??? voting ??? between Cat Lovers & Dog Lovers `
- [ ] A button below the `introduction` named `vote` which redirects to `vote` page. 

## 2. Create a `vote` page
 `vote` page contains:
- [ ]  `number of voters` 🔢 text box this is required as per the backend
- [ ] 1 checkbox for `Cat Lovers` and another checkbox for `Dog Lovers`
- [ ] A button `vote`. This button sends the votes from the front-end to back-end.
- [ ] This is for `back-end` : increase the counter until the `number of voters` are done voting. Then redirect the page to `results`  

## 3. Create a `results` page 
`results` page contains: 
- [ ] just an image. If `votes of CAT Lovers` > `votes of DOG Lovers` -> "AN IMAGE OF CAT" else "AN IMAGE OF DOG"
